### ISSUE TITLE
Please merge the order_by fix.

### ISSUE THREAD

**Issue by lu-zero** [dhamaniasad/Flask-WhooshAlchemy#4]
https://github.com/gyllstromk/Flask-WhooshAlchemy/pull/32

**Comment by dhamaniasad** [comment]
@lu-zero Can you verify that the fix works? I'll merge this and push a new version on PyPI if that's the case.

**Comment by lu-zero** [comment]
Verified and seems working fine.

**Comment by dhamaniasad** [comment]
@lu-zero I have merged the pull request, and a new version shall be on PyPI soon. I will notify you once it's available. Thanks for contributing!

**Comment by dhamaniasad** [comment]
@lu-zero Version `0.6.3` contains this fix and is available on PyPI now.

**Comment by lu-zero** [comment]
Thanks a lot! I'll update requirements now
